title: "Vividha"
email: rvividha@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hey:)
baseurl: "/" 
url: "/portfolio-template" 
twitter_username: vvdha
github_username:  V2dha

sass:
  sass_dir: _sass

icon: ./assets/img/bitmoji.png
